// app/layout.tsx
import { Providers } from './provider';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  return (
    <html lang='en'>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}

// import { ThemeProvider } from "@chakra-ui/react";
// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import { Providers } from './providers'

// const inter = Inter({ subsets: ["latin"] });

// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {// app/layout.tsx
//   return (
//     <html lang="en">
//       <body > 
//         <Providers>{children}</Providers>
//       </body>
//     </html>
//   );
// }

